config/routes.rb
Catarse::Application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for(
    :users,
    {
      path: '',
      path_names:   { sign_in: :login, sign_out: :logout, sign_up: :sign_up },
      controllers:  { omniauth_callbacks: :omniauth_callbacks, passwords: :passwords }
    }
  )

  devise_scope :user do
    post '/sign_up', {to: 'devise/registrations#create', as: :sign_up}
  end

  get '/thank_you' => "static#thank_you"

  filter :locale, exclude: /\/auth\//

  mount CatarseMoip::Engine => "/", as: :catarse_moip
  mount CatarsePagarme::Engine => "/", as: :catarse_pagarme
  mount CatarseApi::Engine => "/api", as: :catarse_api
 #mount CatarseWepay::Engine => "/", as: :catarse_wepay
  mount Dbhero::Engine => "/dbhero", as: :dbhero

  resources :bank_accounts, except: [:destroy, :index] do
    member do
      get 'confirm'
      put 'request_refund'
    end
  end

  resources :categories, only: [] do
    member do
      get :subscribe, to: 'categories/subscriptions#create'
      get :unsubscribe, to: 'categories/subscriptions#destroy'
    end
  end
  resources :auto_complete_projects, only: [:index]
  resources :donations, only: [:create] do
    collection do
      get :confirm
    end
  end
  resources :auto_complete_cities, only: [:index]
  resources :flexible_projects do
    member do
      get :publish
      get :finish
    end
  end
  resources :projects, only: [ :index, :create, :update, :edit, :new, :show] do
    resources :accounts, only: [:create, :update]
    resources :posts, controller: 'projects/posts', only: [ :destroy ]
    resources :rewards do
      post :sort, on: :member
    end
    resources :contributions, {except: [:index], controller: 'projects/contributions'} do
      collection do
        get :fallback_create, to: 'projects/contributions#create'
      end
      member do
        get 'toggle_anonymous'
        get :second_slip
        get :no_account_refund
      end
      put :credits_checkout, on: :member
    end

    get 'video', on: :collection
    member do
      get 'insights'
      put 'pay'
      get 'embed'
      get 'video_embed'
      get 'embed_panel'
      get 'send_to_analysis'
      get 'publish'
    end
  end
  resources :users do
    resources :credit_cards, controller: 'users/credit_cards', only: [ :destroy ]
    member do
      get :unsubscribe_notifications
      get :credits
      get :settings
      get :billing
      get :reactivate
      post :new_password
    end

    resources :unsubscribes, only: [:create]
    member do
      get 'projects'
      put 'unsubscribe_update'
      put 'update_email'
      put 'update_password'
    end
  end

  get "/terms-of-use" => 'high_voltage/pages#show', id: 'terms_of_use'
  get "/privacy-policy" => 'high_voltage/pages#show', id: 'privacy_policy'
  get "/start" => 'high_voltage/pages#show', id: 'start'
  get "/jobs" => 'high_voltage/pages#show', id: 'jobs'
  get "/hello" => 'high_voltage/pages#show', id: 'hello'
  get "/press" => 'high_voltage/pages#show', id: 'press'
  get "/assets" => 'high_voltage/pages#show', id: 'assets'
  get "/guides" => 'high_voltage/pages#show', id: 'guides', as: :guides
  get "/new-admin" => 'high_voltage/pages#show', id: 'new_admin'
  get "/explore" => 'high_voltage/pages#show', id: 'explore'
  get "/team" => 'high_voltage/pages#show', id: 'team'
  get "/flex" => 'high_voltage/pages#show', id: 'flex'


  # User permalink profile
  constraints SubdomainConstraint do
    get "/", to: 'users#show'
  end

  # Root path should be after channel constraints
  root to: 'projects#index'

  namespace :reports do
    resources :contribution_reports_for_project_owners, only: [:index]
  end

  # Feedback form
  resources :feedbacks, only: [:create]

  namespace :admin do
    resources :projects, only: [ :index, :update, :destroy ] do
      member do
        put 'approve'
        put 'push_to_online'
        put 'reject'
        put 'push_to_draft'
        put 'push_to_trash'
      end
    end

    resources :financials, only: [ :index ]

    resources :contributions, only: [ :index, :update, :show ] do
      member do
        get :second_slip
        put 'pay'
        put 'change_reward'
        put 'refund'
        put 'trash'
        put 'request_refund'
        put 'chargeback'
        put 'gateway_refund'
      end
    end
    resources :users, only: [ :index ]

    namespace :reports do
      resources :contribution_reports, only: [ :index ]
    end
  end

  resource :api_token, only: [:show]

  get "/:permalink" => "projects#show", as: :project_by_slug

end

app/models/concerns/project/all_or_nothing_state_validator.rb
# -*- coding: utf-8 -*-
# This module handles with default state validation
module Project::AllOrNothingStateValidator
  extend ActiveSupport::Concern

  included do
    with_options if: ->(x) { x.mode == 'aon' } do |wg| 
      # Validation for in_analysis? only state
      wg.with_options if: :in_analysis? do |wo|
        wo.validates_presence_of :city
        wo.validates_length_of :name, maximum: Project::NAME_MAXLENGTH
      end

      # Start validations when project state
      # is included on ON_ANALYSIS_TO_END_STATE
      wg.with_options if: -> (x) { Project::ON_ANALYSIS_TO_END_STATES.include? x.state } do |wo| 
        wo.validates_presence_of :goal, :online_days
      end
    end
  end
end

app/models/concerns/project/base_validator.rb
# -*- coding: utf-8 -*-
# This module handles with default project state validation
module Project::BaseValidator
  extend ActiveSupport::Concern

  included do
    # All valid states for projects in_analysis to end of publication
    ON_ANALYSIS_TO_END_STATES = %w(in_analysis approved online successful waiting_funds failed).freeze

    # All valid states for projects approved to end of publication
    ON_ONLINE_TO_END_STATES = %w(online successful waiting_funds failed).freeze

    # Start validations when project state
    # is included on ON_ANALYSIS_TO_END_STATE
    with_options if: -> (x) { ON_ANALYSIS_TO_END_STATES.include? x.state } do |wo| 
      wo.validates_presence_of :about_html, :headline, :goal

      wo.validates_presence_of :uploaded_image,
        unless: ->(project) { project.video_thumbnail.present? }

      wo.validate do
        [:uploaded_image, :about_html, :name].each do |attr|
          self.user.errors.add_on_blank(attr)
        end

        self.user.errors.each do |error, error_message|
          self.errors.add('user.' + error.to_s, error_message)
        end
      end
    end

    with_options if: -> (x) { ON_ONLINE_TO_END_STATES.include? x.state } do |wo| 
      wo.validate do
        if self.account && (self.account.agency.try(:size) || 0) < 4
          self.errors['account.agency_size'] << "Agência deve ter pelo menos 4 dígitos"
        end
      end
    end

  end
end

app/models/concerns/project/custom_validators.rb
module Project::CustomValidators
  extend ActiveSupport::Concern

  included do
    @@routes = Rails.application.routes.routes
    validate :permalink_cant_be_route, allow_nil: true
    # This code might come back in a near future
    #validate :ensure_at_least_one_reward_validation, unless: :is_flexible?


    def self.get_routes
      @@mapped_routes ||= @@routes.inject(Set.new) do |memo, item|
        memo << $1 if item.path.spec.to_s.match(/^\/([\w]+)\S/)
        memo
      end
    end

    def self.permalink_on_routes?(permalink)
      permalink && self.get_routes.include?(permalink.downcase)
    end

    def permalink_cant_be_route
      errors.add(:permalink, I18n.t("activerecord.errors.models.project.attributes.permalink.invalid")) if Project.permalink_on_routes?(permalink)
    end
    
    def ensure_at_least_one_reward_validation
      errors.add(
        'rewards.size',
        I18n.t("activerecord.errors.models.project.attributes.rewards.at_least_one")
      ) if rewards.empty?
    end
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::BaseController
  layout 'catarse_bootstrap'

  has_scope :by_user_email, :by_id, :pg_search, :user_name_contains, :with_state, :by_category_id, :order_by
  has_scope :between_created_at, :between_expires_at, :between_online_date, :between_updated_at, :goal_between, using: [ :start_at, :ends_at ]

  before_filter do
    @total_projects = Project.count(:all)
  end

  [:approve, :reject, :push_to_draft, :push_to_trash, :push_to_online].each do |name|
    define_method name do
      @project = Project.find params[:id]
      @project.send("#{name.to_s}")
      redirect_to :back
    end
  end

  def destroy
    @project = Project.find params[:id]
    if @project.can_push_to_trash?
      @project.push_to_trash
    end

    redirect_to admin_projects_path
  end

  def update
    resource.update_attributes(permitted_params)
    super
  end

  protected
  def permitted_params
    params.require(:project).permit(resource.attribute_names.map(&:to_sym))
  end

  def collection
    @scoped_projects = apply_scopes(Project).without_state('deleted')
    @projects = @scoped_projects.page(params[:page])
  end
end

app/controllers/projects/contributions_controller.rb
class Projects::ContributionsController < ApplicationController
  inherit_resources
  actions :index, :show, :new, :update, :review, :create
  skip_before_filter :verify_authenticity_token, only: [:moip]
  after_filter :verify_authorized, except: [:index]
  belongs_to :project
  before_filter :detect_old_browsers, only: [:new, :create]

  helper_method :engine

  def edit
    authorize resource
    if resource.reward.try(:sold_out?)
      flash[:alert] = t('.reward_sold_out')
      return redirect_to new_project_contribution_path(@project)
    end
    return render :existing_payment if resource.payments.exists?
  end

  def update
    authorize resource
    resource.update_attributes(permitted_params)
    resource.update_user_billing_info
    render json: {message: 'updated'}
  end

  def show
    authorize resource
    @title = t('projects.contributions.show.title')
  end

  def new
    @contribution = Contribution.new(project: parent, value: (params[:amount].presence || 10).to_i)
    authorize @contribution

    @title = t('projects.contributions.new.title', name: @project.name)
    load_rewards

    if params[:reward_id] && (@selected_reward = @project.rewards.find params[:reward_id]) && !@selected_reward.sold_out?
      @contribution.reward = @selected_reward
      @contribution.value = "%0.0f" % @selected_reward.minimum_value
    end
  end

  def create
    @title = t('projects.contributions.create.title')
    @contribution = parent.contributions.new.localized
    @contribution.user = current_user
    @contribution.value = permitted_params[:value]
    @contribution.origin = Origin.process_hash(referral)
    @contribution.reward_id = (params[:contribution][:reward_id].to_i == 0 ? nil : params[:contribution][:reward_id])
    authorize @contribution
    @contribution.update_current_billing_info
    create! do |success,failure|
      failure.html do
        flash[:alert] = resource.errors.full_messages.to_sentence
        load_rewards
        render :new
      end
      success.html do
        flash[:notice] = nil
        session[:thank_you_contribution_id] = @contribution.id
        return redirect_to edit_project_contribution_path(project_id: @project.id, id: @contribution.id)
      end
    end
    @thank_you_id = @project.id
  end

  def no_account_refund
    authorize resource
  end

  def second_slip
    authorize resource
    redirect_to resource.details.ordered.first.second_slip_path
  end

  def toggle_anonymous
    authorize resource
    resource.toggle!(:anonymous)
    return render nothing: true
  end

  protected
  def load_rewards
    if @project.rewards.present?
      empty_reward = Reward.new(minimum_value: 0, description: t('projects.contributions.new.no_reward'))
      @rewards = [empty_reward] + @project.rewards.remaining.order(:minimum_value)
    else
      @rewards = []
    end
  end

  def permitted_params
    params.require(:contribution).permit(policy(resource).permitted_attributes)
  end

  def engine
    PaymentEngines.find_engine('Pagarme')
  end
end

app/controllers/projects/posts_controller.rb
class Projects::PostsController < ApplicationController
  def parent
    @project ||= Project.find params[:project_id]
  end

  def destroy
    authorize resource
    resource.destroy

    flash[:notice] = t('project.delete.posts')
    redirect_to edit_project_path(parent, anchor: 'posts')
  end

  def resource
    @post ||= parent.posts.find params[:id]
  end
end

app/controllers/projects_controller.rb
# coding: utf-8
class ProjectsController < ApplicationController

  after_filter :verify_authorized, except: %i[show index video video_embed embed embed_panel about_mobile]
  after_filter :redirect_user_back_after_login, only: %i[index show]
  before_action :authorize_and_build_resources, only: %i[edit]

  has_scope :pg_search, :by_category_id
  has_scope :recent, :expiring, :successful, :in_funding, :recommended, :not_expired, type: :boolean

  helper_method :project_comments_canonical_url, :resource, :collection

  respond_to :html
  respond_to :json, only: [:index, :show, :update]

  before_action :referral_it!

  def index
    respond_to do |format|
      format.html do
        return render_index_for_xhr_request if request.xhr?
      end
      format.atom do
        return render layout: false, locals: {projects: projects}
      end
      format.rss { redirect_to projects_path(format: :atom), :status => :moved_permanently }
    end
  end

  def new
    @project = Project.new user: current_user
    authorize @project
    @project.rewards.build
  end

  def create
    @project = Project.new
    @project.attributes = permitted_params.merge(
      user: current_user,
      origin: Origin.process_hash(referral))
    authorize @project
    if @project.save
      redirect_to insights_project_path(@project)
    else
      render :new
    end
  end

  def destroy
    authorize resource
    destroy!
  end

  def send_to_analysis
    authorize resource
    resource_action :send_to_analysis, :analysis_success
  end

  def publish
    authorize resource
    resource_action :push_to_online
  end

  def insights
    authorize resource, :update?
  end

  def update
    authorize resource

    #need to check this before setting new attributes
    should_validate = should_use_validate

    resource.localized.attributes = permitted_params

    if resource.save(validate: should_validate)
      flash[:notice] = t('project.update.success')
    else
      flash[:notice] = t('project.update.failed')
      build_dependencies
      return render :edit
    end

    if params[:anchor]
      redirect_to edit_project_path(@project, anchor: params[:anchor])
    else
      redirect_to edit_project_path(@project, anchor: 'home')
    end
  end

  def show
    fb_admins_add(resource.user.facebook_id) if resource.user.facebook_id
    @post ||= resource.posts.where(id: params[:project_post_id].to_i).first if params[:project_post_id].present?
  end

  def video
    project = Project.new(video_url: params[:url])
    render json: project.video.to_json
  rescue VideoInfo::UrlError
    render json: nil
  end

  def embed
    resource
    render partial: 'card', layout: 'embed', locals: {embed_link: true, ref: (params[:ref] || 'embed')}
  end

  def embed_panel
    resource
    render partial: 'project_embed'
  end

  protected
  def authorize_and_build_resources
    authorize resource
    build_dependencies
  end

  def build_dependencies
    @posts_count = resource.posts.count(:all)
    @user = resource.user
    @user.links.build
    @post =  (params[:project_post_id].present? ? resource.posts.where(id: params[:project_post_id]).first : resource.posts.build)
    @rewards = @project.rewards.rank(:row_order)
    @rewards = @project.rewards.build unless @rewards.present?

    resource.build_account unless resource.account
  end

  def resource_action action_name, success_redirect=nil
    if resource.send(action_name)
      if resource.origin.nil? && referral.present?
        resource.update_attribute(
          :origin_id, Origin.process_hash(referral).try(:id))
      end

      flash[:notice] = t("projects.#{action_name.to_s}")
      if success_redirect
        redirect_to edit_project_path(@project, anchor: success_redirect)
      else
        redirect_to insights_project_path(@project)
      end
    else
      flash.now[:notice] = t("projects.#{action_name.to_s}_error")
      build_dependencies
      render :edit
    end
  end

  def render_index_for_xhr_request
    render partial: 'projects/card',
      collection: projects,
      layout: false,
      locals: {ref: "explore", wrapper_class: 'w-col w-col-4 u-marginbottom-20'}
  end

  def projects
    page = params[:page] || 1
    @projects ||= apply_scopes(Project.visible.order_status).
      most_recent_first.
      includes(:project_total, :user, :category).
      page(page).per(18)
  end

  def should_use_validate
    resource.valid?
  end

  def permitted_params
    params.require(:project).permit(policy(resource).permitted_attributes)
  end

  def resource
    @project ||= (params[:permalink].present? ? Project.by_permalink(params[:permalink]).first! : Project.find(params[:id]))
  end

  def project_comments_canonical_url
    url = project_by_slug_url(resource.permalink, protocol: 'http', subdomain: 'www').split('/')
    url.delete_at(3) #remove language from url
    url.join('/')
  end
end

app/views/catarse_bootstrap/projects/_aon_nav_actions.html.slim
- if @project.draft?
   = link_to t('.send'), send_to_analysis_project_path(@project), class: 'btn btn-medium'
- if @project.approved?
   = link_to publish_project_path(@project), class: 'btn btn-medium' do
    = t('.publish')
    | &nbsp;&nbsp;
    span.fa.fa-chevron-right

app/views/catarse_bootstrap/projects/_aon_preview_explanation.html.slim
.u-text-center
  .w-container
    .w-row
      .w-col.w-col-8.w-col-push-2
        .fontweight-semibold.fontsize-large.u-margintop-40= t('projects.dashboard_preview.aon.header_subtitle') 
        p.fontsize-base= t('projects.dashboard_preview.aon.header_text') 
        .w-row.u-marginbottom-30
          .w-col.w-col-3
          .w-col.w-col-6
            input.w-input.text-field value="#{project_by_slug_url(@project.permalink, locale: '')}" type="text"
          .w-col.w-col-3
      .w-col.w-col-2

app/views/catarse_bootstrap/projects/_dashboard_announce_expiration.html.slim
.w-row.u-marginbottom-60
  .w-col.w-col-1
  .w-col.w-col-10
    .card.card-big.card-terciary.u-radius
      .fontsize-base= t('.explanation_01')
      .u-text-center.fontsize-large.u-marginbottom-40.u-margintop-40
        span.card.u-radius
          = l(FlexibleProject::FINAL_LAP_INTERVAL.days.from_now.to_date)
          | &nbsp; às 23h59m59s
      .fontsize-base= t('.explanation_02')

.w-row
  .w-col.w-col-2
  .w-col.w-col-8
    .w-row
      .w-col.w-col-6.w-col-small-6.w-col-tiny-6._w-col-small-6.w-sub-col
        = link_to t('no'), insights_project_path(@project), class: 'btn btn-large btn-terciary'
      .w-col.w-col-6.w-col-small-6.w-col-tiny-6.w-sub-col
        = link_to t('yes'), finish_flexible_project_path(@project.flexible_project), class: 'btn btn-large'
  .w-col.w-col-2

app/views/catarse_bootstrap/projects/_dashboard_basics.html.slim
= simple_form_for @project, html: { class: 'project-form w-form' } do |form|
  .w-section.section
    .w-container
      .w-row
        .w-col.w-col-10.w-col-push-1
          .w-form
              = @project.display_errors(:basics)
              - if (current_user && current_user.admin?)
                = form.input :user_id, as: :string, 
                  wrapper: :two_columns,
                  wrapper_class: 'w-row u-marginbottom-20 card card-terciary medium',
                  label_wrapper_html: { class: 'w-col w-col-5' },
                  text_field_wrapper_html: { class: 'w-col w-col-7' },
                  input_html: { class: 'positive medium', required: true },
                  validation_text: false

                = form.input :all_tags, as: :string, 
                  wrapper: :two_columns,
                  wrapper_class: 'w-row u-marginbottom-30 card card-terciary medium',
                  label_wrapper_html: { class: 'w-col w-col-5 w-subcol' },
                  text_field_wrapper_html: { class: 'w-col w-col-7 w-sub-col' },
                  input_html: { class: 'positive medium', required: false },
                  validation_text: false

              = form.input :name, as: :string, 
                wrapper: :two_columns,
                wrapper_class: 'w-row u-marginbottom-30 card card-terciary medium',
                label_wrapper_html: { class: 'w-col w-col-5 w-subcol' },
                text_field_wrapper_html: { class: 'w-col w-col-7 w-sub-col' },
                input_html: { class: 'positive medium', required: true, maxlength: Project::NAME_MAXLENGTH },
                validation_text: false

              = form.input :permalink, as: :string, 
                wrapper: :two_columns_with_postfix,
                wrapper_class: 'w-row u-marginbottom-30 card card-terciary medium',
                label_wrapper_html: { class: 'w-col w-col-5 w-subcol' },
                text_field_wrapper_html: { class: 'w-col w-col-7 w-sub-col' },
                input_html: { class: 'postfix positive medium', required: true },
                field_wrapper_html: { class: 'w-col w-col-8 w-col-small-6 w-col-tiny-6' },
                validation_text: false,
                preppend_text_wrapper_html: { class: 'w-col w-col-4 w-col-small-6 w-col-tiny-6 text-field prefix no-hover medium prefix-permalink' },
                preppend_input_text: 'www.catarse.me/',
                preppend_input_text_wrapper_html: { class: 'fontcolor-secondary u-text-center fontsize-smallest' }

              = form.association :category, as: :select, 
                collection: Category.order(:name_pt),
                prompt: t('simple_form.prompts.project.category'),
                wrapper: :two_columns,
                wrapper_class: 'w-row u-marginbottom-30 card card-terciary medium',
                label_wrapper_html: { class: 'w-col w-col-5 w-subcol' },
                text_field_wrapper_html: { class: 'w-col w-col-7' },
                input_html: { class: 'w-select text-field positive medium', required: true },
                validation_text: false

              #city-input-wrapper data-searchpath=auto_complete_cities_path
                .w-row.u-marginbottom-30.card.card-terciary.medium
                  .w-col.w-col-5.w-sub-col
                    label.fontweight-semibold.fontsize-base=t('.city')
                    label.field-label.fontsize-smallest.fontcolor-secondary=t('simple_form.hints.project.city')
                  .w-col.w-col-7
                    = text_field_tag :city_name, ( @project.city.show_name if @project.city ), class: 'string optional w-input text-field w-input text-field positive city-search-input', autocomplete: "off"
                    input#project_city_id.w-hidden name="project[city_id]" type="text" /
                    .table-outer.search-pre-result.w-hidden

    .section
      .w-container
        .w-row
          .w-col.w-col-4.w-col-push-4
            = hidden_field_tag 'anchor', 'basics'
            = form.button :submit, t('.form.submit'), class:'btn btn-large', id: 'basics-save'

app/views/catarse_bootstrap/projects/_dashboard_budget.html.slim
= simple_form_for @project, html: { class: 'project-form w-form' } do |form|
  .w-section.section
    .w-container
      .w-row
        .w-col.w-col-10.w-col-push-1
          .w-form
            = @project.display_errors(:budget)
            = form.input :budget, as: :text,
              wrapper: :two_columns,
              wrapper_class: 'w-row u-marginbottom-30 card card-terciary',
              input_html: { class: 'redactor positive', required: false },
              validation_text: false
  .w-section.section
    .w-container
      .w-row
        .w-col.w-col-4.w-col-push-4
          = hidden_field_tag 'anchor', 'budget'
          = form.button :submit, t('.submit'), class:'btn btn-large', id: 'budget-save'

app/views/catarse_bootstrap/projects/_dashboard_card.html.slim
= simple_form_for @project, html: { class: 'project-form w-form' } do |form|
  .w-section.section
    .w-container
      .w-row
        .w-col.w-col-8
          .w-form
              = @project.display_errors(:card)
              = form.input :uploaded_image, as: :file,
                wrapper: :two_columns,
                wrapper_class: 'w-row u-marginbottom-30 card card-terciary',
                label_wrapper_html: { class: 'w-col w-col-5 w-subcol' },
                text_field_wrapper_html: { class: 'w-col w-col-6' },
                input_html: { required: false },
                validation_text: false

              = form.input :headline, as: :text,
                wrapper: :two_columns,
                wrapper_class: 'w-row u-marginbottom-30 card card-terciary',
                label_wrapper_html: { class: 'w-col w-col-5 w-subcol' },
                text_field_wrapper_html: { class: 'w-col w-col-7' },
                input_html: { class: 'positive', rows: 3, required: false, maxlength: Project::HEADLINE_MAXLENGTH },
                validation_text: false
        .w-col.w-col-4
          = render 'card'
  .w-section.section
    .w-container
      .w-row
        .w-col.w-col-4.w-col-push-4
          = hidden_field_tag 'anchor', 'card'
          = form.hidden_field :project_id, value: @project.id
          = form.button :submit, t('.submit'), class:'btn btn-large', id: 'budget-save'

app/views/catarse_bootstrap/projects/_dashboard_nav.html.slim
- edit = defined?(edit_page) || false
= content_for :body_class, 'body-project open'
#project-nav
  .project-nav-wrapper
    nav.w-section.dashboard-nav.side
      = link_to (@project.published? ? project_by_slug_path(@project.permalink) : '#preview'), id: 'dashboard_preview_link', class: 'w-inline-block dashboard-project-name' , data: {target: '#dashboard_preview', tab_group: 'edit'} do
        - if @project.uploaded_image.present?
          img.thumb-project-dashboard src="#{@project.display_image(:project_thumb_large)}" width="114"
        - else
          img.thumb-project-dashboard src="#{image_path('thumb-project.png')}" width="114"
        .fontcolor-negative.lineheight-tight.fontsize-small= @project.name
        = image_tag("catarse_bootstrap/badge-#{@project.mode}-h.png", class: 'u-margintop-10', width: 80)

      #info-links
        = link_to insights_project_path(@project), class: 'dashboard-nav-link-left ' , id: 'dashboard_home_link', data: {tab_group: 'edit'} do
          span.fa.fa-bar-chart.fa-lg.fa-fw
          = t('.start_tab')
        - if @project.published?
          = link_to (edit ? '#reports' : edit_project_path(@project, anchor: 'reports')), id: 'dashboard_reports_link', class: 'dashboard-nav-link-left ' , data: {target: '#dashboard_reports', tab_group: 'edit'} do
            span.fa.fa.fa-table.fa-lg.fa-fw
            = t('.reports_tab')
          = link_to (edit ? '#posts' : edit_project_path(@project, anchor: 'posts')), id: 'dashboard_posts_link', class: 'dashboard-nav-link-left u-marginbottom-30' , data: {target: '#dashboard_posts', tab_group: 'edit'} do
            span.fa.fa-bullhorn.fa-fw.fa-lg
            = t('.posts_tab')
            | &nbsp
            span.badge= @project.posts.count

      .edit-project-div
        - if @project.published? && !@project.is_flexible?
          button#toggle-edit-menu.dashboard-nav-link-left
            span.fa.fa-pencil.fa-fw.fa-lg
            = t('.edit_project')
          #edit-menu-items.w-hidden
            = render partial: 'dashboard_nav_links', locals: {edit: edit}
        - else
          = render partial: 'dashboard_nav_links', locals: {edit: edit}

          .btn-send-draft-fixed
            = render "#{@project.mode}_nav_actions"
  a.btn-dashboard href="#"
    span.fa.fa-bars.fa-lg

app/views/catarse_bootstrap/projects/_flex_preview_explanation.html.slim
- link_to_project = link_to(project_by_slug_url(@project.permalink, locale: ''), project_by_slug_url(@project.permalink, locale: ''))
.u-text-center
  .w-container
    .w-row
      .w-col.w-col-8.w-col-push-2
        .fontweight-semibold.fontsize-large.u-margintop-40= t('projects.dashboard_preview.flex.header_subtitle') 
        p.fontsize-base= t('projects.dashboard_preview.flex.header_text', link: link_to_project).html_safe 
        .w-row.u-marginbottom-30
          .w-col.w-col-3
          .w-col.w-col-6
            = link_to t('projects.dashboard_preview.flex.publish_btn_html'), publish_flexible_project_path(@project.flexible_project), class: 'w-button btn btn-large'
          .w-col.w-col-3
          .w-col.w-col-2