config/routes.rb
Catarse::Application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for(
    :users,
    {
      path: '',
      path_names:   { sign_in: :login, sign_out: :logout, sign_up: :sign_up },
      controllers:  { omniauth_callbacks: :omniauth_callbacks, passwords: :passwords }
    }
  )

  devise_scope :user do
    post '/sign_up', {to: 'devise/registrations#create', as: :sign_up}
  end

  get '/thank_you' => "static#thank_you"

  filter :locale, exclude: /\/auth\//

  mount CatarseMoip::Engine => "/", as: :catarse_moip
  mount CatarsePagarme::Engine => "/", as: :catarse_pagarme
  mount CatarseApi::Engine => "/api", as: :catarse_api
 #mount CatarseWepay::Engine => "/", as: :catarse_wepay
  mount Dbhero::Engine => "/dbhero", as: :dbhero

  resources :bank_accounts, except: [:destroy, :index] do
    member do
      get 'confirm'
      put 'request_refund'
    end
  end

  resources :categories, only: [] do
    member do
      get :subscribe, to: 'categories/subscriptions#create'
      get :unsubscribe, to: 'categories/subscriptions#destroy'
    end
  end
  resources :auto_complete_projects, only: [:index]
  resources :donations, only: [:create] do
    collection do
      get :confirm
    end
  end
  resources :auto_complete_cities, only: [:index]
  resources :flexible_projects do
    member do
      get :publish
      get :finish
    end
  end
  resources :projects, only: [ :index, :create, :update, :edit, :new, :show] do
    resources :accounts, only: [:create, :update]
    resources :posts, controller: 'projects/posts', only: [ :destroy ]
    resources :rewards do
      post :sort, on: :member
    end
    resources :contributions, {except: [:index], controller: 'projects/contributions'} do
      collection do
        get :fallback_create, to: 'projects/contributions#create'
      end
      member do
        get 'toggle_anonymous'
        get :second_slip
        get :no_account_refund
      end
      put :credits_checkout, on: :member
    end

    get 'video', on: :collection
    member do
      get 'insights'
      put 'pay'
      get 'embed'
      get 'video_embed'
      get 'embed_panel'
      get 'send_to_analysis'
      get 'publish'
    end
  end
  resources :users do
    resources :credit_cards, controller: 'users/credit_cards', only: [ :destroy ]
    member do
      get :unsubscribe_notifications
      get :credits
      get :settings
      get :billing
      get :reactivate
      post :new_password
    end

    resources :unsubscribes, only: [:create]
    member do
      get 'projects'
      put 'unsubscribe_update'
      put 'update_email'
      put 'update_password'
    end
  end

  get "/terms-of-use" => 'high_voltage/pages#show', id: 'terms_of_use'
  get "/privacy-policy" => 'high_voltage/pages#show', id: 'privacy_policy'
  get "/start" => 'high_voltage/pages#show', id: 'start'
  get "/jobs" => 'high_voltage/pages#show', id: 'jobs'
  get "/hello" => 'high_voltage/pages#show', id: 'hello'
  get "/press" => 'high_voltage/pages#show', id: 'press'
  get "/assets" => 'high_voltage/pages#show', id: 'assets'
  get "/guides" => 'high_voltage/pages#show', id: 'guides', as: :guides
  get "/new-admin" => 'high_voltage/pages#show', id: 'new_admin'
  get "/explore" => 'high_voltage/pages#show', id: 'explore'
  get "/team" => 'high_voltage/pages#show', id: 'team'
  get "/flex" => 'high_voltage/pages#show', id: 'flex'


  # User permalink profile
  constraints SubdomainConstraint do
    get "/", to: 'users#show'
  end

  # Root path should be after channel constraints
  root to: 'projects#index'

  namespace :reports do
    resources :contribution_reports_for_project_owners, only: [:index]
  end

  # Feedback form
  resources :feedbacks, only: [:create]

  namespace :admin do
    resources :projects, only: [ :index, :update, :destroy ] do
      member do
        put 'approve'
        put 'push_to_online'
        put 'reject'
        put 'push_to_draft'
        put 'push_to_trash'
      end
    end

    resources :financials, only: [ :index ]

    resources :contributions, only: [ :index, :update, :show ] do
      member do
        get :second_slip
        put 'pay'
        put 'change_reward'
        put 'refund'
        put 'trash'
        put 'request_refund'
        put 'chargeback'
        put 'gateway_refund'
      end
    end
    resources :users, only: [ :index ]

    namespace :reports do
      resources :contribution_reports, only: [ :index ]
    end
  end

  resource :api_token, only: [:show]

  get "/:permalink" => "projects#show", as: :project_by_slug

end

app/models/concerns/contribution/custom_validators.rb
module Contribution::CustomValidators
  extend ActiveSupport::Concern

  included do
    validate :reward_must_be_from_project
    validate :value_must_be_at_least_rewards_value
    validate :should_not_contribute_if_maximum_contributions_been_reached, on: :create

    def reward_must_be_from_project
      return unless reward
      errors.add(:reward, I18n.t('contribution.reward_must_be_from_project')) unless reward.project == project
    end

    def value_must_be_at_least_rewards_value
      return unless reward
      errors.add(:value, I18n.t('contribution.value_must_be_at_least_rewards_value', minimum_value: reward.display_minimum)) unless value.to_f >= reward.minimum_value
    end

    def should_not_contribute_if_maximum_contributions_been_reached
      return unless reward && reward.maximum_contributions && reward.maximum_contributions > 0
      errors.add(:reward, I18n.t('contribution.should_not_contribute_if_maximum_contributions_been_reached')) if reward.sold_out?
    end
  end
end

app/models/concerns/project/flexible_handler.rb
#
# FlexibleHandler module
# this module handles with flexible project
# methods, when is calling via project
#
module Project::FlexibleHandler
  extend ActiveSupport::Concern

  included do

    #
    # check if project is flexible.
    # project should be have a flexible project
    # relation created.
    #
    # usage:
    #
    # project = Project.find
    # project.is_flexible?
    #
    def is_flexible?
      # TODO: maybe move this to handles on database function.
      self.flexible_project.present?
    end

  end
end

app/controllers/admin/contributions_controller.rb
class Admin::ContributionsController < Admin::BaseController
  layout 'catarse_bootstrap'
  has_scope :project_name_contains, :search_on_acquirer, :by_user_id, :by_gateway, :by_payment_id, :by_payment_method, :user_name_contains, :user_email_contains, :with_state
  has_scope :between_values, using: [ :start_at, :ends_at ], allow_blank: true
  before_filter :set_title

  def self.contribution_actions
    %w[pay refund trash chargeback request_refund].each do |action|
      define_method action do
        if resource.send(action)
          flash[:notice] = I18n.t("admin.contributions.messages.successful.#{action}")
        else
          flash[:notice] = t("activerecord.errors.models.contribution")
        end
        redirect_to admin_contributions_path(params[:local_params])
      end
    end
  end
  contribution_actions

  def gateway_refund
    resource.direct_refund
    respond_to do |format|
      format.html do
        return redirect_to admin_contributions_path(params[:local_params])
      end
      format.json do
        return render json: []
      end
    end

  end

  def update
    if params[:contribution]
      Contribution.update(params[:id], params[:contribution])
      head :ok, content_type: "text/html"
    else
      update!
    end
  end

  def change_reward
    contribution.change_reward! params[:reward_id]
    flash[:notice] = I18n.t('admin.contributions.messages.successful.change_reward')
    redirect_to admin_contributions_path(params[:local_params])
  end

  protected
  def set_title
    @title = t("admin.contributions.index.title")
  end

  def contribution
    resource.contribution
  end

  def resource
    ContributionDetail.find_by_id params[:id]
  end

  def collection
    @contributions = apply_scopes(ContributionDetail).reorder("contribution_details.contribution_id DESC").page(params[:page])
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::BaseController
  layout 'catarse_bootstrap'

  has_scope :by_user_email, :by_id, :pg_search, :user_name_contains, :with_state, :by_category_id, :order_by
  has_scope :between_created_at, :between_expires_at, :between_online_date, :between_updated_at, :goal_between, using: [ :start_at, :ends_at ]

  before_filter do
    @total_projects = Project.count(:all)
  end

  [:approve, :reject, :push_to_draft, :push_to_trash, :push_to_online].each do |name|
    define_method name do
      @project = Project.find params[:id]
      @project.send("#{name.to_s}")
      redirect_to :back
    end
  end

  def destroy
    @project = Project.find params[:id]
    if @project.can_push_to_trash?
      @project.push_to_trash
    end

    redirect_to admin_projects_path
  end

  def update
    resource.update_attributes(permitted_params)
    super
  end

  protected
  def permitted_params
    params.require(:project).permit(resource.attribute_names.map(&:to_sym))
  end

  def collection
    @scoped_projects = apply_scopes(Project).without_state('deleted')
    @projects = @scoped_projects.page(params[:page])
  end
end

app/controllers/projects/contributions_controller.rb
class Projects::ContributionsController < ApplicationController
  inherit_resources
  actions :index, :show, :new, :update, :review, :create
  skip_before_filter :verify_authenticity_token, only: [:moip]
  after_filter :verify_authorized, except: [:index]
  belongs_to :project
  before_filter :detect_old_browsers, only: [:new, :create]

  helper_method :engine

  def edit
    authorize resource
    if resource.reward.try(:sold_out?)
      flash[:alert] = t('.reward_sold_out')
      return redirect_to new_project_contribution_path(@project)
    end
    return render :existing_payment if resource.payments.exists?
  end

  def update
    authorize resource
    resource.update_attributes(permitted_params)
    resource.update_user_billing_info
    render json: {message: 'updated'}
  end

  def show
    authorize resource
    @title = t('projects.contributions.show.title')
  end

  def new
    @contribution = Contribution.new(project: parent, value: (params[:amount].presence || 10).to_i)
    authorize @contribution

    @title = t('projects.contributions.new.title', name: @project.name)
    load_rewards

    if params[:reward_id] && (@selected_reward = @project.rewards.find params[:reward_id]) && !@selected_reward.sold_out?
      @contribution.reward = @selected_reward
      @contribution.value = "%0.0f" % @selected_reward.minimum_value
    end
  end

  def create
    @title = t('projects.contributions.create.title')
    @contribution = parent.contributions.new.localized
    @contribution.user = current_user
    @contribution.value = permitted_params[:value]
    @contribution.origin = Origin.process_hash(referral)
    @contribution.reward_id = (params[:contribution][:reward_id].to_i == 0 ? nil : params[:contribution][:reward_id])
    authorize @contribution
    @contribution.update_current_billing_info
    create! do |success,failure|
      failure.html do
        flash[:alert] = resource.errors.full_messages.to_sentence
        load_rewards
        render :new
      end
      success.html do
        flash[:notice] = nil
        session[:thank_you_contribution_id] = @contribution.id
        return redirect_to edit_project_contribution_path(project_id: @project.id, id: @contribution.id)
      end
    end
    @thank_you_id = @project.id
  end

  def no_account_refund
    authorize resource
  end

  def second_slip
    authorize resource
    redirect_to resource.details.ordered.first.second_slip_path
  end

  def toggle_anonymous
    authorize resource
    resource.toggle!(:anonymous)
    return render nothing: true
  end

  protected
  def load_rewards
    if @project.rewards.present?
      empty_reward = Reward.new(minimum_value: 0, description: t('projects.contributions.new.no_reward'))
      @rewards = [empty_reward] + @project.rewards.remaining.order(:minimum_value)
    else
      @rewards = []
    end
  end

  def permitted_params
    params.require(:contribution).permit(policy(resource).permitted_attributes)
  end

  def engine
    PaymentEngines.find_engine('Pagarme')
  end
end

app/controllers/projects/posts_controller.rb
class Projects::PostsController < ApplicationController
  def parent
    @project ||= Project.find params[:project_id]
  end

  def destroy
    authorize resource
    resource.destroy

    flash[:notice] = t('project.delete.posts')
    redirect_to edit_project_path(parent, anchor: 'posts')
  end

  def resource
    @post ||= parent.posts.find params[:id]
  end
end

app/controllers/projects_controller.rb
# coding: utf-8
class ProjectsController < ApplicationController

  after_filter :verify_authorized, except: %i[show index video video_embed embed embed_panel about_mobile]
  after_filter :redirect_user_back_after_login, only: %i[index show]
  before_action :authorize_and_build_resources, only: %i[edit]

  has_scope :pg_search, :by_category_id
  has_scope :recent, :expiring, :successful, :in_funding, :recommended, :not_expired, type: :boolean

  helper_method :project_comments_canonical_url, :resource, :collection

  respond_to :html
  respond_to :json, only: [:index, :show, :update]

  before_action :referral_it!

  def index
    respond_to do |format|
      format.html do
        return render_index_for_xhr_request if request.xhr?
      end
      format.atom do
        return render layout: false, locals: {projects: projects}
      end
      format.rss { redirect_to projects_path(format: :atom), :status => :moved_permanently }
    end
  end

  def new
    @project = Project.new user: current_user
    authorize @project
    @project.rewards.build
  end

  def create
    @project = Project.new
    @project.attributes = permitted_params.merge(
      user: current_user,
      origin: Origin.process_hash(referral))
    authorize @project
    if @project.save
      redirect_to insights_project_path(@project)
    else
      render :new
    end
  end

  def destroy
    authorize resource
    destroy!
  end

  def send_to_analysis
    authorize resource
    resource_action :send_to_analysis, :analysis_success
  end

  def publish
    authorize resource
    resource_action :push_to_online
  end

  def insights
    authorize resource, :update?
  end

  def update
    authorize resource

    #need to check this before setting new attributes
    should_validate = should_use_validate

    resource.localized.attributes = permitted_params

    if resource.save(validate: should_validate)
      flash[:notice] = t('project.update.success')
    else
      flash[:notice] = t('project.update.failed')
      build_dependencies
      return render :edit
    end

    if params[:anchor]
      redirect_to edit_project_path(@project, anchor: params[:anchor])
    else
      redirect_to edit_project_path(@project, anchor: 'home')
    end
  end

  def show
    fb_admins_add(resource.user.facebook_id) if resource.user.facebook_id
    @post ||= resource.posts.where(id: params[:project_post_id].to_i).first if params[:project_post_id].present?
  end

  def video
    project = Project.new(video_url: params[:url])
    render json: project.video.to_json
  rescue VideoInfo::UrlError
    render json: nil
  end

  def embed
    resource
    render partial: 'card', layout: 'embed', locals: {embed_link: true, ref: (params[:ref] || 'embed')}
  end

  def embed_panel
    resource
    render partial: 'project_embed'
  end

  protected
  def authorize_and_build_resources
    authorize resource
    build_dependencies
  end

  def build_dependencies
    @posts_count = resource.posts.count(:all)
    @user = resource.user
    @user.links.build
    @post =  (params[:project_post_id].present? ? resource.posts.where(id: params[:project_post_id]).first : resource.posts.build)
    @rewards = @project.rewards.rank(:row_order)
    @rewards = @project.rewards.build unless @rewards.present?

    resource.build_account unless resource.account
  end

  def resource_action action_name, success_redirect=nil
    if resource.send(action_name)
      if resource.origin.nil? && referral.present?
        resource.update_attribute(
          :origin_id, Origin.process_hash(referral).try(:id))
      end

      flash[:notice] = t("projects.#{action_name.to_s}")
      if success_redirect
        redirect_to edit_project_path(@project, anchor: success_redirect)
      else
        redirect_to insights_project_path(@project)
      end
    else
      flash.now[:notice] = t("projects.#{action_name.to_s}_error")
      build_dependencies
      render :edit
    end
  end

  def render_index_for_xhr_request
    render partial: 'projects/card',
      collection: projects,
      layout: false,
      locals: {ref: "explore", wrapper_class: 'w-col w-col-4 u-marginbottom-20'}
  end

  def projects
    page = params[:page] || 1
    @projects ||= apply_scopes(Project.visible.order_status).
      most_recent_first.
      includes(:project_total, :user, :category).
      page(page).per(18)
  end

  def should_use_validate
    resource.valid?
  end

  def permitted_params
    params.require(:project).permit(policy(resource).permitted_attributes)
  end

  def resource
    @project ||= (params[:permalink].present? ? Project.by_permalink(params[:permalink]).first! : Project.find(params[:id]))
  end

  def project_comments_canonical_url
    url = project_by_slug_url(resource.permalink, protocol: 'http', subdomain: 'www').split('/')
    url.delete_at(3) #remove language from url
    url.join('/')
  end
end

app/views/catarse_bootstrap/projects/contributions/_aon_faq_box.html.slim
#faq-box.w-hidden-small.w-hidden-tiny.back-faq-box data-ix="new-interaction"
  .w-row.u-marginbottom-30
    .w-col.w-col-2.w-col-small-2.w-col-tiny-2
      img src="https://daks2k3a4ib2z.cloudfront.net/54b440b85608e3f4389db387/5632d273ec8a367d341b4999_badge-aon.png" width="30" /
    .w-col.w-col-10.w-col-small-10.w-col-tiny-10
      .w-inline-block.fontsize-smallest._w-inline-block.fontcolor-secondary=t('projects.contributions.faq.all_or_nothing.explanation')

  .u-marginbottom-20.fontsize-small.fontweight-semibold=t('projects.contributions.faq.all_or_nothing.common_questions')
  ul.w-list-unstyled
    li.list-question.fontsize-smaller.alt-link  #{t('projects.contributions.faq.all_or_nothing.how_contribute')}
    li.list-answer.u-marginbottom-20.fontsize-smaller=t('projects.contributions.faq.all_or_nothing.how_contribute_answer')

    li.list-question.fontsize-smaller.alt-link  #{t('projects.contributions.faq.all_or_nothing.when_made_payment')}
    li.list-answer.u-marginbottom-20.fontsize-smaller=t('projects.contributions.faq.all_or_nothing.when_made_payment_answer')

    li.list-question.fontsize-smaller.alt-link  #{t('projects.contributions.faq.all_or_nothing.when_about_my_payment_data')}
    li.list-answer.u-marginbottom-20.fontsize-smaller=t('projects.contributions.faq.all_or_nothing.when_about_my_payment_data_answer')

    li.list-question.fontsize-smaller.alt-link  #{t('projects.contributions.faq.all_or_nothing.when_project_fails')}
    li.list-answer.u-marginbottom-20.fontsize-smaller=t('projects.contributions.faq.all_or_nothing.when_project_fails_answer')

    li.list-question.fontsize-smaller.alt-link  #{t('projects.contributions.faq.all_or_nothing.when_project_funded')}
    li.list-answer.u-marginbottom-20.fontsize-smaller=raw t('projects.contributions.faq.all_or_nothing.when_project_funded_answer', name: link_to(@project.user.display_name, user_path(@project.user), target: '_blank'))

app/views/catarse_bootstrap/projects/contributions/_selected_reward.html.slim
.card.u-radius.u-marginbottom-20
  .fontsize-smaller.fontweight-semibold.u-marginbottom-20 = t('.value')
  .w-clearfix.u-marginbottom-20
    .fontsize-larger.text-success.u-left = number_to_currency @contribution.localized.value
    = link_to t('.edit'), new_project_contribution_path(@contribution.project), class: 'fontsize-small link-hidden u-right fontweight-semibold'
  - if @project.rewards.present?
    .back-payment-info-reward
      .fontsize-smaller.fontweight-semibold.u-marginbottom-10 = t('.reward')
      .fontsize-smallest
        - if @contribution.reward
          == @contribution.reward.display_description
        - else
          == t('.review_without_reward_html', value: (number_to_currency @contribution.localized.value))

app/views/catarse_bootstrap/projects/contributions/_thank_you.html.slim
.u-marginbottom-30.page-header
  .w-container
    .w-row
      .w-col.w-col-9.w-col-push-1
        .u-text-center.u-marginbottom-20
          = image_tag @project.user.decorate.display_image, class: 'u-round thumb big', alt: @project.user.decorate.display_name
        .u-text-center
          .fontsize-largest.text-success.u-marginbottom-20 = t('.thank_you') 
          .fontsize-base.u-marginbottom-40
            = t('.thank_you_text_html', total: @project.total_contributions, link1: (link_to @project.name, project_by_slug_url(@project.permalink), class: 'alt-link'), link2: (link_to t('.profile_link'), edit_user_path(resource.user, anchor: 'contributions'), class: 'link-hidden fontweight-semibold'))
          .fontsize-base.fontweight-semibold.u-marginbottom-20 = t('.share_back')
        .w-row.u-marginbottom-20
          .w-col.w-col-6.w-col-small-6.w-col-tiny-6.w-sub-col-middle
            div
              img.icon-share-mobile alt="53a3f66e05eb6144171d8edb_facebook-xxl.png" src="http://uploads.webflow.com/54b440b85608e3f4389db387/53a3f66e05eb6144171d8edb_facebook-xxl.png" /
              = link_to "http://www.facebook.com/share.php?u=#{project_by_slug_url(@project.permalink, {ref: 'facebook'})}", target: :_blank, id: 'facebook_share', data: { title: @project.name }, class: 'btn btn-medium btn-fb' do
                = t('.share')
          .w-col.w-col-6.w-col-small-6.w-col-tiny-6
            div
              img.icon-share-mobile alt="53a3f65105eb6144171d8eda_twitter-256.png" src="http://uploads.webflow.com/54b440b85608e3f4389db387/53a3f65105eb6144171d8eda_twitter-256.png" /
              /a.btn.btn-medium.btn-tweet href="#"  Tweet
              = link_to "http://twitter.com/?status=#{t('i_just_contributed', name: @project.name)} #{project_by_slug_url(@project.permalink, ref: 'twitter')}", target: :_blank, id: "twitter_share_button", data: { title: @project.name }, class: 'btn btn-medium btn-tweet' do
                = t('.tweet')

- if @contribution.recommended_projects.exists?
  .section.u-marginbottom-40
    .w-container
      .u-marginbottom-20.fontweight-semibold.fontsize-base.u-text-center= t('.project_recommendations') 
      .w-row
        == render_projects @contribution.recommended_projects.limit(3), 'thankyou', { wrapper_class: 'w-col w-col-4' }

- unless current_user.following_this_category?(@project.category_id)
  .section.section-gray-one
    .w-container
      .fontsize-larger.lineheight-tight.u-text-center.u-marginbottom-40 
        = t('.follow_category', category: @project.category.name_pt)
      .w-row
        .w-col.w-col-4.w-col-push-4
          = link_to "#{t('.follow')} #{@project.category.name_pt}", subscribe_category_path(@project.category), class: 'btn btn-large btn-dark'

app/views/catarse_bootstrap/projects/contributions/_thank_you_slip.html.slim
- payment = @contribution.payments.last
.u-marginbottom-30.page-header
  .w-container
    .w-row
      .w-col.w-col-10.w-col-push-1
        .u-text-center.u-marginbottom-20
          = image_tag @project.user.decorate.display_image, class: 'u-round thumb big', alt: @project.user.decorate.display_name
        .u-text-center
          .fontsize-largest.text-success.u-marginbottom-20 = t('.thank_you') 
          .fontsize-base.u-marginbottom-40
            = t('.thank_you_text_html', email: @contribution.user.email)

.section.u-marginbottom-40
  .w-container
    .w-row
      .w-col.w-col-8.w-col-offset-2
        iframe src="#{payment.gateway_data["boleto_url"]}" width="100%" height="905px" frameborder="0" style="overflow: hidden;"

app/views/catarse_bootstrap/projects/contributions/no_account_refund.html.slim
= render 'shared/header'

#contribution-donation
  .w-section.section-one-column.u-margintop-40
    .w-container
      .w-row.u-text-center.u-marginbottom-60
        .w-col.w-col-2
        .w-col.w-col-8
          .fontsize-larger.u-marginbottom-20 Decida o que fazer com o seu dinheiro no #{CatarseSettings[:company_name]}!

          .fontsize-base= t('.fill_form_text', \
            amount: resource.user.decorator.display_pending_refund_payments_amount)
        .w-col.w-col-2
      .w-row
        .w-col.w-col-6
          .card.medium.card-terciary.u-radius
            = link_to 'Quero doar para o Catarse!', confirm_donations_path, class: 'w-button btn btn-large u-marginbottom-30', method: 'get'
            .fontsize-small ihaaa! Seu dinheiro será utilizado para financiar operações do Catarse e um monte de inovações que vem por aí em 2016. São novidades que certamente ajudarão muita gente. Sinta-se parte do time e ajude a espalhar o financiamento coletivo no Brasil!
        .w-col.w-col-6
          .card.medium.card-terciary.u-radius.u-marginbottom-20
            = link_to 'Quero meu dinheiro de volta!', new_bank_account_path, class: 'w-button btn btn-large u-marginbottom-30'
            .fontsize-small Seu dinheiro será depositado integralmente em sua conta bancária em até 5 dias úteis. Para que possamos efetuar essa transferência, basta nos informar seus dados bancários. Nenhuma taxa é cobrada nesta operação, fique tranquilo!
  .w-section.section.divider.bg-gray.before-footer
    .w-container
      .fontsize-large.u-text-center.fontweight-semibold.u-marginbottom-30 Dúvidas frequentes
      .w-row.u-marginbottom-60
        .w-col.w-col-6
          .card.u-marginbottom-20.u-radius.btn-terciary.show-answer-faq
            .fontsize-base Porque tenho dinheiro no Catarse?
            p.fontsize-small.box-slider.closed   Em algum momento nos últimos 5 anos você apoiou projetos de crowdfunding / financiamento coletivo no Catarse que, infelizmente, não atingiram a meta. Como utilizamos o sistema tudo-ou-nada, se o projeto não bate a meta todos têm direito a receber o dinheiro apoiado de volta. Algumas pessoas não receberam essas devoluções, seja porque o cartão utilizado estava bloqueado no momento da devolução, ou porque não preencheram os dados bancários para realizarmos a devolução.
          .card.u-marginbottom-20.u-radius.btn-terciary.show-answer-faq
            .fontsize-base O que acontece se eu não tomar essa decisão?
            p.fontsize-small.box-slider.closed   No dia 11 de julho de 2015 realizamos uma alteração em nossos Termos de Uso que prevê que caso não consigamos entrar em contato com você por meio dos dados de cadastro registrados na nossa plataforma e nos falte alguma informação bancária para realizar o reembolso, dentro do período de 12 meses a contar da data de encerramento do projeto os valores serão considerados renunciados e poderão ser utilizados pelo CATARSE para reinvestir na plataforma e beneficiar a comunidade. Se você não decidir após 30 dias do envio da primeira notificação, os valores em crédito serão considerados renunciados.
        .w-col.w-col-6
          .card.u-marginbottom-20.u-radius.btn-terciary.show-answer-faq
            .fontsize-base Porque tenho que tomar essa decisão em até 30 dias?
            p.fontsize-small.box-slider.closed   Definimos o prazo de 30 dias a partir da primeira notificação para termos a certeza de que você vai ver essa mensagem e tomar essa decisão. Pense com bastante amor e carinho! Precisamos da sua resposta para que possamos fazer um planejamento financeiro mais preciso e transparente.
          .card.u-marginbottom-20.u-radius.btn-terciary.show-answer-faq
            .fontsize-base Posso usar meus créditos para apoiar outro projeto?
            p.fontsize-small.box-slider.closed Desde o dia 10/11/2014 não é mais possível utilizar os créditos no Catarse para apoiar os projetos na plataforma. Essa é uma das mudanças que fizemos para simplificar o processo de pagamentos e garantir os reembolsos para todo mundo. Clicando em "Quero doar para o Catarse" você apoiará diretamente as operações da plataforma, ajudando-nos a espalhar ainda mais o financiamento coletivo pelo Brasil.
  = render 'shared/footer'