config/routes.rb
Catarse::Application.routes.draw do
  mount RedactorRails::Engine => '/redactor_rails'
  mount JasmineRails::Engine => '/specs' if defined?(JasmineRails)
  devise_for(
    :users,
    {
      path: '',
      path_names:   { sign_in: :login, sign_out: :logout, sign_up: :sign_up },
      controllers:  { omniauth_callbacks: :omniauth_callbacks, passwords: :passwords }
    }
  )

  devise_scope :user do
    post '/sign_up', {to: 'devise/registrations#create', as: :sign_up}
  end

  get '/thank_you' => "static#thank_you"

  filter :locale, exclude: /\/auth\//

  mount CatarseMoip::Engine => "/", as: :catarse_moip
  mount CatarsePagarme::Engine => "/", as: :catarse_pagarme
  mount CatarseApi::Engine => "/api", as: :catarse_api
 #mount CatarseWepay::Engine => "/", as: :catarse_wepay
  mount Dbhero::Engine => "/dbhero", as: :dbhero

  resources :bank_accounts, except: [:destroy, :index] do
    member do
      get 'confirm'
      put 'request_refund'
    end
  end

  resources :categories, only: [] do
    member do
      get :subscribe, to: 'categories/subscriptions#create'
      get :unsubscribe, to: 'categories/subscriptions#destroy'
    end
  end
  resources :auto_complete_projects, only: [:index]
  resources :donations, only: [:create] do
    collection do
      get :confirm
    end
  end
  resources :auto_complete_cities, only: [:index]
  resources :flexible_projects do
    member do
      get :publish
      get :finish
    end
  end
  resources :projects, only: [ :index, :create, :update, :edit, :new, :show] do
    resources :accounts, only: [:create, :update]
    resources :posts, controller: 'projects/posts', only: [ :destroy ]
    resources :rewards do
      post :sort, on: :member
    end
    resources :contributions, {except: [:index], controller: 'projects/contributions'} do
      collection do
        get :fallback_create, to: 'projects/contributions#create'
      end
      member do
        get 'toggle_anonymous'
        get :second_slip
        get :no_account_refund
      end
      put :credits_checkout, on: :member
    end

    get 'video', on: :collection
    member do
      get 'insights'
      put 'pay'
      get 'embed'
      get 'video_embed'
      get 'embed_panel'
      get 'send_to_analysis'
      get 'publish'
    end
  end
  resources :users do
    resources :credit_cards, controller: 'users/credit_cards', only: [ :destroy ]
    member do
      get :unsubscribe_notifications
      get :credits
      get :settings
      get :billing
      get :reactivate
      post :new_password
    end

    resources :unsubscribes, only: [:create]
    member do
      get 'projects'
      put 'unsubscribe_update'
      put 'update_email'
      put 'update_password'
    end
  end

  get "/terms-of-use" => 'high_voltage/pages#show', id: 'terms_of_use'
  get "/privacy-policy" => 'high_voltage/pages#show', id: 'privacy_policy'
  get "/start" => 'high_voltage/pages#show', id: 'start'
  get "/jobs" => 'high_voltage/pages#show', id: 'jobs'
  get "/hello" => 'high_voltage/pages#show', id: 'hello'
  get "/press" => 'high_voltage/pages#show', id: 'press'
  get "/assets" => 'high_voltage/pages#show', id: 'assets'
  get "/guides" => 'high_voltage/pages#show', id: 'guides', as: :guides
  get "/new-admin" => 'high_voltage/pages#show', id: 'new_admin'
  get "/explore" => 'high_voltage/pages#show', id: 'explore'
  get "/team" => 'high_voltage/pages#show', id: 'team'
  get "/flex" => 'high_voltage/pages#show', id: 'flex'


  # User permalink profile
  constraints SubdomainConstraint do
    get "/", to: 'users#show'
  end

  # Root path should be after channel constraints
  root to: 'projects#index'

  namespace :reports do
    resources :contribution_reports_for_project_owners, only: [:index]
  end

  # Feedback form
  resources :feedbacks, only: [:create]

  namespace :admin do
    resources :projects, only: [ :index, :update, :destroy ] do
      member do
        put 'approve'
        put 'push_to_online'
        put 'reject'
        put 'push_to_draft'
        put 'push_to_trash'
      end
    end

    resources :financials, only: [ :index ]

    resources :contributions, only: [ :index, :update, :show ] do
      member do
        get :second_slip
        put 'pay'
        put 'change_reward'
        put 'refund'
        put 'trash'
        put 'request_refund'
        put 'chargeback'
        put 'gateway_refund'
      end
    end
    resources :users, only: [ :index ]

    namespace :reports do
      resources :contribution_reports, only: [ :index ]
    end
  end

  resource :api_token, only: [:show]

  get "/:permalink" => "projects#show", as: :project_by_slug

end

app/models/concerns/contribution/custom_validators.rb
module Contribution::CustomValidators
  extend ActiveSupport::Concern

  included do
    validate :reward_must_be_from_project
    validate :value_must_be_at_least_rewards_value
    validate :should_not_contribute_if_maximum_contributions_been_reached, on: :create

    def reward_must_be_from_project
      return unless reward
      errors.add(:reward, I18n.t('contribution.reward_must_be_from_project')) unless reward.project == project
    end

    def value_must_be_at_least_rewards_value
      return unless reward
      errors.add(:value, I18n.t('contribution.value_must_be_at_least_rewards_value', minimum_value: reward.display_minimum)) unless value.to_f >= reward.minimum_value
    end

    def should_not_contribute_if_maximum_contributions_been_reached
      return unless reward && reward.maximum_contributions && reward.maximum_contributions > 0
      errors.add(:reward, I18n.t('contribution.should_not_contribute_if_maximum_contributions_been_reached')) if reward.sold_out?
    end
  end
end

app/models/concerns/contribution/state_machine_handler.rb
module Contribution::StateMachineHandler
  extend ActiveSupport::Concern

  included do
    state_machine :state, initial: :pending do
      state :pending, value: 'pending'
      state :waiting_confirmation, value: 'waiting_confirmation'
      state :confirmed, value: 'confirmed'
      state :canceled, value: 'canceled'
      state :refunded, value: 'refunded'
      state :requested_refund, value: 'requested_refund'
      state :chargeback, value: 'chargeback'
      state :refunded_and_canceled, value: 'refunded_and_canceled'
      state :deleted, value: 'deleted'
      state :invalid_payment, value: 'invalid_payment'

      event :push_to_trash do
        transition all => :deleted
      end

      event :pendent do
        transition all => :pending
      end

      event :waiting do
        transition pending: :waiting_confirmation
      end

      event :invalid do
        transition all => :invalid_payment
      end

      event :confirm do
        transition [:pending, :confirmed, :waiting_confirmation, :canceled, :deleted] => :confirmed
      end

      event :cancel do
        transition all => :canceled
      end

      event :request_refund do
        transition confirmed: :requested_refund, if: ->(contribution){
          contribution.user.credits >= contribution.value && !contribution.credits
        }
      end

      event :refund do
        transition [:requested_refund, :confirmed] => :refunded
      end

      event :hide do
        transition all => :refunded_and_canceled
      end

      after_transition do |contribution, transition|
        contribution.notify_observers :"from_#{transition.from}_to_#{transition.to}"

        to_column = "#{transition.to}_at".to_sym
        if contribution.has_attribute?(to_column)
          contribution.update_attribute to_column, DateTime.current
        end
      end

      after_transition any => [:refunded_and_canceled] do |contribution, transition|
        contribution.notify_to_contributor :refunded_and_canceled
      end
    end
  end
end

app/controllers/admin/contributions_controller.rb
class Admin::ContributionsController < Admin::BaseController
  layout 'catarse_bootstrap'
  has_scope :project_name_contains, :search_on_acquirer, :by_user_id, :by_gateway, :by_payment_id, :by_payment_method, :user_name_contains, :user_email_contains, :with_state
  has_scope :between_values, using: [ :start_at, :ends_at ], allow_blank: true
  before_filter :set_title

  def self.contribution_actions
    %w[pay refund trash chargeback request_refund].each do |action|
      define_method action do
        if resource.send(action)
          flash[:notice] = I18n.t("admin.contributions.messages.successful.#{action}")
        else
          flash[:notice] = t("activerecord.errors.models.contribution")
        end
        redirect_to admin_contributions_path(params[:local_params])
      end
    end
  end
  contribution_actions

  def gateway_refund
    resource.direct_refund
    respond_to do |format|
      format.html do
        return redirect_to admin_contributions_path(params[:local_params])
      end
      format.json do
        return render json: []
      end
    end

  end

  def update
    if params[:contribution]
      Contribution.update(params[:id], params[:contribution])
      head :ok, content_type: "text/html"
    else
      update!
    end
  end

  def change_reward
    contribution.change_reward! params[:reward_id]
    flash[:notice] = I18n.t('admin.contributions.messages.successful.change_reward')
    redirect_to admin_contributions_path(params[:local_params])
  end

  protected
  def set_title
    @title = t("admin.contributions.index.title")
  end

  def contribution
    resource.contribution
  end

  def resource
    ContributionDetail.find_by_id params[:id]
  end

  def collection
    @contributions = apply_scopes(ContributionDetail).reorder("contribution_details.contribution_id DESC").page(params[:page])
  end
end

app/controllers/projects/contributions_controller.rb
class Projects::ContributionsController < ApplicationController
  inherit_resources
  actions :index, :show, :new, :update, :review, :create
  skip_before_filter :verify_authenticity_token, only: [:moip]
  after_filter :verify_authorized, except: [:index]
  belongs_to :project
  before_filter :detect_old_browsers, only: [:new, :create]

  helper_method :engine

  def edit
    authorize resource
    if resource.reward.try(:sold_out?)
      flash[:alert] = t('.reward_sold_out')
      return redirect_to new_project_contribution_path(@project)
    end
    return render :existing_payment if resource.payments.exists?
  end

  def update
    authorize resource
    resource.update_attributes(permitted_params)
    resource.update_user_billing_info
    render json: {message: 'updated'}
  end

  def show
    authorize resource
    @title = t('projects.contributions.show.title')
  end

  def new
    @contribution = Contribution.new(project: parent, value: (params[:amount].presence || 10).to_i)
    authorize @contribution

    @title = t('projects.contributions.new.title', name: @project.name)
    load_rewards

    if params[:reward_id] && (@selected_reward = @project.rewards.find params[:reward_id]) && !@selected_reward.sold_out?
      @contribution.reward = @selected_reward
      @contribution.value = "%0.0f" % @selected_reward.minimum_value
    end
  end

  def create
    @title = t('projects.contributions.create.title')
    @contribution = parent.contributions.new.localized
    @contribution.user = current_user
    @contribution.value = permitted_params[:value]
    @contribution.origin = Origin.process_hash(referral)
    @contribution.reward_id = (params[:contribution][:reward_id].to_i == 0 ? nil : params[:contribution][:reward_id])
    authorize @contribution
    @contribution.update_current_billing_info
    create! do |success,failure|
      failure.html do
        flash[:alert] = resource.errors.full_messages.to_sentence
        load_rewards
        render :new
      end
      success.html do
        flash[:notice] = nil
        session[:thank_you_contribution_id] = @contribution.id
        return redirect_to edit_project_contribution_path(project_id: @project.id, id: @contribution.id)
      end
    end
    @thank_you_id = @project.id
  end

  def no_account_refund
    authorize resource
  end

  def second_slip
    authorize resource
    redirect_to resource.details.ordered.first.second_slip_path
  end

  def toggle_anonymous
    authorize resource
    resource.toggle!(:anonymous)
    return render nothing: true
  end

  protected
  def load_rewards
    if @project.rewards.present?
      empty_reward = Reward.new(minimum_value: 0, description: t('projects.contributions.new.no_reward'))
      @rewards = [empty_reward] + @project.rewards.remaining.order(:minimum_value)
    else
      @rewards = []
    end
  end

  def permitted_params
    params.require(:contribution).permit(policy(resource).permitted_attributes)
  end

  def engine
    PaymentEngines.find_engine('Pagarme')
  end
end

app/views/catarse_bootstrap/admin/contributions/index.html.slim
= render 'shared/header_big'
.w-row.admin.admin-contributions
  h1
    = @title = t('admin.management.title')
    ' :
  h3 = t('admin.filter.title')
  = simple_form_for '', url: admin_contributions_path, method: :get do |form|
    .w-row
      .w-col-2.w-col
        = form.input 'between_values[start_at]', as: :integer, label: t(".between_values")
      .w-col-2.w-col.no-label
        = form.input 'between_values[ends_at]', as: :integer, label: ''
      .w-col-3.w-col
        = form.input :user_email_contains, as: :string, label: t('.email')
      .w-col-2.w-col
        = form.input :by_payment_id, as: :string, label: t('.payment_id')
      .w-col-2.w-col
        = form.input :with_state, collection: Payment.state_names, label: t('admin.filter.with_state'), as: :select, selected: params[:with_state], include_blank: true
    .w-row
      .w-col-3.w-col
        = form.input :project_name_contains, as: :string, label: t('.project')
      .w-col-2.w-col
        = form.input :user_name_contains, as: :string, label: t('.user')
      .w-col-2.w-col
        = form.input :search_on_acquirer, as: :string, label: t('.acquirer'), input_html: { placeholder: t('.placeholders.acquirer'), title: t('.placeholders.acquirer'), value: current_scopes[:search_on_acquirer] }
      .w-col-2.w-col
        = form.input :by_gateway, collection: Payment.pluck("DISTINCT gateway"), label: t('admin.filter.by_gateway'), as: :select, selected: params[:by_gateway], include_blank: true
      .w-col-2.w-col
        = form.button :submit, t('admin.filter.submit'), class: 'button medium negative'

  = paginate @contributions
  - if @contributions.empty?
    = t('.no_contributions')
  - else
    - @contributions.each do |contribution|
      table.table.admin-contributions
        thead.card.card-secondary
          tr
            th= t('.contribution')
            th= t('.project')
            th= t('.project_state')
            th= t('.user')
            th= t('.value')
            th= t('.payment_tax')
            th= t('.reward')
            th= t('.emails')
            th= t('.anonymous')
            th= t('.credits')
            th= t('.last_state')
            th= t('.state')
            th
        tbody
          tr id=contribution.contribution_id
            td
              = link_to contribution.contribution_id, admin_contribution_path(contribution.id)
            td.project_info title=contribution.project.name
              = link_to project_by_slug_path(permalink: contribution.project.permalink) do
                = image_tag contribution.project.display_image, class: 'project_img'
            td.project_info
              = contribution.project.state
            td.user_info title=contribution.user.display_name
              = link_to edit_user_path(contribution.user) do
                = image_tag contribution.user.display_image, class: 'user_img'
              .user_id= best_in_place [:admin, contribution.contribution], :user_id, method: :put, type: :input
            td= contribution.value
            td= contribution.gateway_fee
            td.w-col-6.w-col.reward.project-events-dropdown title=("#{contribution.reward.display_minimum} - #{contribution.reward.description}" if contribution.reward)
              - if contribution.reward
                span = contribution.reward.display_minimum
              - else
                | -
              .w-dropdown-toggle.dropdown-toggle.project-admin-menu
                = link_to 'javascript:void(0);', data: {toggle: 'dropdown'}, class: 'w-icon-dropdown-toggle btn btn-dark round positive dropdown-toggle' do
                  span.caret
              nav.w-dropdown-list.dropdown-list
                = link_to t('.no_reward'), change_reward_admin_contribution_path(contribution, reward_id: nil), method: :put, class: 'w-dropdown-link dropdown-link fontsize-smaller'
                - contribution.available_rewards.each do |reward|
                  = link_to reward.minimum_value, change_reward_admin_contribution_path(contribution, reward_id: reward.id, local_params: params), method: :put, class: 'w-dropdown-link dropdown-link fontsize-smaller'

            td.key
              strong= t('.details.payer_email') 
              br/
              = contribution.payer_email
              br/
              strong= t('.details.normal_email')
              br/
              = contribution.user.email
            td.checkbox= best_in_place [:admin, contribution.contribution], :anonymous, method: :put, type: :checkbox, collection: [t('no'), t('yes')]
            td= (contribution.credits? ? t('yes') : t('no'))
            td= contribution.last_state_name
            td= contribution.state
            td.w-col-6.w-col
              .w-dropdown-toggle.dropdown-toggle.project-admin-menu
                = link_to 'javascript:void(0);', data: {toggle: 'dropdown'}, class: 'w-icon-dropdown-toggle btn btn-dark round positive dropdown-toggle' do
                  span.caret
              nav.w-dropdown-list.dropdown-list
                - unless %w[paid refunded].include?(contribution.state)
                  = link_to t('admin.contributions.index.confirm_contribution'), pay_admin_contribution_path(contribution, local_params: params), method: :put, class: 'w-dropdown-link dropdown-link fontsize-smaller'

                - if contribution.paid?
                  = link_to t('admin.contributions.index.request_refund'), request_refund_admin_contribution_path(contribution, local_params: params), method: :put, class: 'w-dropdown-link dropdown-link fontsize-smaller'
                - if contribution.paid? || contribution.deleted? || contribution.pending_refund? || contribution.refunded?
                  = link_to t('admin.contributions.index.direct_refund'), gateway_refund_admin_contribution_path(contribution, local_params: params), method: :put, class: 'w-dropdown-link dropdown-link fontsize-smaller'

                - if contribution.pending_refund? || contribution.paid? || contribution.deleted?
                  = link_to t('admin.contributions.index.refund_contribution'), refund_admin_contribution_path(contribution, local_params: params), method: :put, class: 'w-dropdown-link dropdown-link fontsize-smaller'

                - if contribution.paid?
                  = link_to t('admin.contributions.index.chargeback'), chargeback_admin_contribution_path(contribution, local_params: params), method: :put, class: 'w-dropdown-link dropdown-link fontsize-smaller'

                - unless contribution.paid?
                  = link_to t('admin.contributions.index.push_to_trash'), trash_admin_contribution_path(contribution, local_params: params), method: :put, class: 'w-dropdown-link dropdown-link fontsize-smaller'

                - if contribution.second_slip_path
                  = link_to t('admin.contributions.index.second_slip'), contribution.second_slip_path, class: 'w-dropdown-link dropdown-link fontsize-smaller', target: :blank

          tr class='detail_tr' id="contribution_details-#{contribution.id}"
            td colspan='11'
              table.table style='border: 1px #ededed solid; margin-bottom: 30px'
                thead
                  th= t('.key')
                  th= t('.details.payment_id')
                  th= t('.details.payment_method')
                  th= t('.details.acquirer_tid')
                  th= t('.details.acquirer_name')
                  th= t('.details.payment_choice')
                  th= t('.details.installments')
                  th= t('.details.created_at')
                tbody
                  tr
                    td= contribution.key
                    td= contribution.gateway_id
                    td= contribution.gateway
                    - if contribution.gateway_data
                      td= contribution.gateway_data["acquirer_tid"]
                      td= contribution.gateway_data["acquirer_name"]
                    - else
                      td &nbsp;
                      td &nbsp;
                    td= contribution.payment_method
                    td= contribution.installments
                    td= l(contribution.created_at, format: :simple) if contribution.created_at.present?
= paginate @contributions

= render 'shared/footer_big'

app/views/catarse_bootstrap/admin/contributions/show.html.slim
= render 'shared/header_big'

.w-row
  h3= t('.contribution_info', key: resource.key)
  p
    strong= t('.payment_method')
    | &nbsp;
    = resource.gateway
  p
    strong= t('.payment_fee')
    | &nbsp;
    = number_to_currency resource.gateway_fee, unit: 'R$', precision: 2, delimiter: '.'
  p
    strong= t('.payment_id')
    | &nbsp;
    = resource.gateway_id
  p
    strong= t('.payer_email')
    | &nbsp;
    = resource.payer_email
  p
    strong= t('.user_email')
    | &nbsp;
    = resource.user.email
  p
    strong= t('.payment_choice')
    | &nbsp;
    = resource.payment_method
  p
    strong= t('.created_at')
    | &nbsp;
    = l(resource.created_at) if resource.created_at.present?

= render 'shared/footer_big'